### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 163-164

### ISSUE THREAD

**Issue by tiann** [biermeester/Pylinter#48]
When my python file is in a uncode path,such as F://Temp/携程/process.py
the pylinter just doesn't work!
I open the console, it show like this:
Writing file /F/Temp/携程/process.py with encoding UTF-8
Exception in thread Thread-19:
Traceback (most recent call last):
  File ".\threading.py", line 532, in **bootstrap_inner
  File ".\pylinter.py", line 487, in run
  File ".\subprocess.py", line 633, in __init**
  File ".\subprocess.py", line 842, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 163-164: ordinal not in range(128)

could you please solve this problem? i'm so confused.

**Comment by biermeester** [comment]
I've looked into this, but there doesn't seem to be an easy fix. In fact I'm not even sure if it's fixable from within Pylinter, since it has to do with character encoding of the console. Also, Python 2 and 3 seem to handle encoding in the Popen object differently.

So, sorry, but for the time being the only 'fix' is to rename your folder to 'Ctrip'.

**Comment by tiann** [comment]
@biermeester I make sure the directory is assic latters now and it works well, thank you !
