### ISSUE TITLE
Icons become black 

### ISSUE THREAD

**Issue by pradyunsg** [biermeester/Pylinter#53]
On color schemes with light backgrounds, the icons become practically black.

![pylint-icons](https://cloud.githubusercontent.com/assets/3275593/2753430/2775c3a8-c934-11e3-8191-358164644dd7.png)
(Font: Source code Pro, Theme:Default, Color Scheme: IDLE)

**Comment by biermeester** [comment]
SublimeText colorizes the gutter icons according to the coloring that's defined for the regions they belong to. Since themes don't recognize Pylinter regions by default, the coloring can go wrong.

Of course we cannot modify every color scheme out there so Pylinter comes with only one adapted scheme: MonokaiPylinter. In this scheme, the regions (and their colors) that Pylinter uses are defined. If you copy those definitions to your scheme of choice, all colors should return.

Just copy and paste the following XML into the color scheme you want to use. (Paste it into the first array tag you come across)

```
<dict>
    <key>name</key>
    <string>Pylinter</string>
    <key>scope</key>
    <string>pylinter</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#AE81FF</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>PylinterW</string>
    <key>scope</key>
    <string>pylinter.W</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#FFAE00</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>PylinterR</string>
    <key>scope</key>
    <string>pylinter.R</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#6E6E6E</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>PylintereE</string>
    <key>scope</key>
    <string>pylinter.E</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#ED2D2D</string>
    </dict>
</dict>
<dict>
    <key>name</key>
    <string>PylintereF</string>
    <key>scope</key>
    <string>pylinter.F</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#5CCBD1</string>
    </dict>
</dict>
```

**Comment by pradyunsg** [comment]
@biermeester This should be mentioned in the README, along with `use_icons` settings information.
